
sudo: required

services:
  - docker

language: python

env:
  global:
    - DOCKER_REPOSITORY=cedricrupb/neural-algorithm-selection

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile

install:
  - docker pull ${DOCKER_REPOSITORY}:last_successful_build || true
  - docker pull ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} || true
  - docker build -t cedricrupb/task-backend ./task_backend
  - |
    if [ ! -f "pesco.zip" ] ; then
      ./scripts/setup-pesco.sh
    fi
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .
  - docker run -d --name ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}

script:
  - docker ps | grep -i ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} 

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
