
sudo: required

services:
  - docker

language: python

env:
  global:
    - DOCKER_REPOSITORY=cedricrupb/neural-algorithm-selection
    - BASE_REPOSITORY=cedricrupb/nas-base

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile

install:
  - docker pull ${DOCKER_REPOSITORY}:last_successful_build || true
  - docker pull ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} || true
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} -t ${DOCKER_REPOSITORY}:latest --pull=true .
  - docker run -d ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}

script:
  - docker ps | grep -i ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
